[package]
name = "fenbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_yaml = "0.9"
serenity = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }